// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGitHubCLI() {
  return window['go']['main']['App']['CheckGitHubCLI']();
}

export function TriggerCreateAMI(arg1, arg2, arg3) {
  return window['go']['main']['App']['TriggerCreateAMI'](arg1, arg2, arg3);
}

export function TriggerCreateAMIBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['TriggerCreateAMIBatch'](arg1, arg2, arg3);
}

export function TriggerPromotionAMI(arg1, arg2, arg3) {
  return window['go']['main']['App']['TriggerPromotionAMI'](arg1, arg2, arg3);
}

// Histórico
export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetHistoryByType(arg1) {
  return window['go']['main']['App']['GetHistoryByType'](arg1);
}

export function AddHistoryEntry(arg1) {
  return window['go']['main']['App']['AddHistoryEntry'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

// Autenticação Onvio
export function AuthenticateWithCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuthenticateWithCredentials'](arg1, arg2, arg3);
}

export function AuthenticateWithCompanyID(arg1, arg2) {
  return window['go']['main']['App']['AuthenticateWithCompanyID'](arg1, arg2);
}

// Gerenciamento de Credenciais
export function GetSavedLogins(arg1) {
  return window['go']['main']['App']['GetSavedLogins'](arg1);
}

export function GetSavedCompanyIDs(arg1) {
  return window['go']['main']['App']['GetSavedCompanyIDs'](arg1);
}

export function SaveLogin(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveLogin'](arg1, arg2, arg3, arg4);
}

export function SaveCompanyID(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCompanyID'](arg1, arg2, arg3);
}

export function DeleteLogin(arg1, arg2) {
  return window['go']['main']['App']['DeleteLogin'](arg1, arg2);
}

export function DeleteCompanyID(arg1, arg2) {
  return window['go']['main']['App']['DeleteCompanyID'](arg1, arg2);
}

export function UpdateLoginLastUsed(arg1, arg2) {
  return window['go']['main']['App']['UpdateLoginLastUsed'](arg1, arg2);
}

export function UpdateCompanyIDLastUsed(arg1, arg2) {
  return window['go']['main']['App']['UpdateCompanyIDLastUsed'](arg1, arg2);
}

// Informações da Sessão
export function GetSessionInfo(arg1, arg2) {
  return window['go']['main']['App']['GetSessionInfo'](arg1, arg2);
}

// Geradores e Formatadores
export function GenerateCPF() {
  return window['go']['main']['App']['GenerateCPF']();
}

export function ValidateCPF(arg1) {
  return window['go']['main']['App']['ValidateCPF'](arg1);
}

export function GenerateCNPJ() {
  return window['go']['main']['App']['GenerateCNPJ']();
}

export function ValidateCNPJ(arg1) {
  return window['go']['main']['App']['ValidateCNPJ'](arg1);
}

export function GenerateUUID() {
  return window['go']['main']['App']['GenerateUUID']();
}

export function GenerateLoremIpsum(arg1) {
  return window['go']['main']['App']['GenerateLoremIpsum'](arg1);
}

export function ApplyCPFMask(arg1) {
  return window['go']['main']['App']['ApplyCPFMask'](arg1);
}

export function ApplyCNPJMask(arg1) {
  return window['go']['main']['App']['ApplyCNPJMask'](arg1);
}

export function FormatOnlyDigits(arg1) {
  return window['go']['main']['App']['FormatOnlyDigits'](arg1);
}
