// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGitHubCLI() {
  return window['go']['main']['App']['CheckGitHubCLI']();
}


// Geradores e Formatadores
export function GenerateCPF() {
  return window['go']['main']['App']['GenerateCPF']();
}

export function ValidateCPF(arg1) {
  return window['go']['main']['App']['ValidateCPF'](arg1);
}

export function GenerateCNPJ() {
  return window['go']['main']['App']['GenerateCNPJ']();
}

export function ValidateCNPJ(arg1) {
  return window['go']['main']['App']['ValidateCNPJ'](arg1);
}

export function GenerateUUID() {
  return window['go']['main']['App']['GenerateUUID']();
}

export function GenerateLoremIpsum(arg1) {
  return window['go']['main']['App']['GenerateLoremIpsum'](arg1);
}

export function ApplyCPFMask(arg1) {
  return window['go']['main']['App']['ApplyCPFMask'](arg1);
}

export function ApplyCNPJMask(arg1) {
  return window['go']['main']['App']['ApplyCNPJMask'](arg1);
}

export function FormatOnlyDigits(arg1) {
  return window['go']['main']['App']['FormatOnlyDigits'](arg1);
}
