// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHistoryEntry(arg1:main.HistoryEntry):Promise<void>;

export function ApplyCNPJMask(arg1:string):Promise<string>;

export function ApplyCPFMask(arg1:string):Promise<string>;

export function AuthenticateWithCompanyID(arg1:string,arg2:string):Promise<main.AuthResult>;

export function AuthenticateWithCredentials(arg1:string,arg2:string,arg3:string):Promise<main.AuthResult>;

export function CheckGitHubCLI():Promise<main.GHStatus>;

export function ClearHistory():Promise<void>;

export function DeleteCompanyID(arg1:string,arg2:string):Promise<void>;

export function DeleteHistoryEntry(arg1:string):Promise<void>;

export function DeleteLogin(arg1:string,arg2:string):Promise<void>;

export function FormatOnlyDigits(arg1:string):Promise<string>;

export function GenerateCNPJ():Promise<main.DocumentResult>;

export function GenerateCPF():Promise<main.DocumentResult>;

export function GenerateLoremIpsum(arg1:number):Promise<string>;

export function GenerateUUID():Promise<string>;

export function GetHistory():Promise<Array<main.HistoryEntry>>;

export function GetHistoryByType(arg1:string):Promise<Array<main.HistoryEntry>>;

export function GetSavedCompanyIDs(arg1:string):Promise<Array<main.SavedCompanyID>>;

export function GetSavedLogins(arg1:string):Promise<Array<main.SavedLogin>>;

export function GetSessionInfo(arg1:string,arg2:string):Promise<main.SessionInfo>;

export function SaveCompanyID(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveLogin(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TriggerCreateAMI(arg1:string,arg2:string,arg3:string):Promise<main.WorkflowResult>;

export function TriggerCreateAMIBatch(arg1:string,arg2:Array<string>,arg3:string):Promise<main.BatchResult>;

export function TriggerPromotionAMI(arg1:string,arg2:string,arg3:string):Promise<main.WorkflowResult>;

export function UpdateCompanyIDLastUsed(arg1:string,arg2:string):Promise<void>;

export function UpdateLoginLastUsed(arg1:string,arg2:string):Promise<void>;

export function ValidateCNPJ(arg1:string):Promise<main.DocumentResult>;

export function ValidateCPF(arg1:string):Promise<main.DocumentResult>;
