// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyCNPJMask(arg1:string):Promise<string>;

export function ApplyCPFMask(arg1:string):Promise<string>;

export function CheckGitHubCLI():Promise<main.GHStatus>;

export function DecompressGzip(arg1:string):Promise<string>;

export function FormatOnlyDigits(arg1:string):Promise<string>;

export function GenerateCNPJ():Promise<main.DocumentResult>;

export function GenerateCPF():Promise<main.DocumentResult>;

export function GenerateLoremIpsum(arg1:number):Promise<string>;

export function GenerateRandomName():Promise<string>;

export function GenerateUUID():Promise<string>;

export function ValidateCNPJ(arg1:string):Promise<main.DocumentResult>;

export function ValidateCPF(arg1:string):Promise<main.DocumentResult>;
